version: '3.7'

services:
  ffas:
    image: ffas
    ports:
      - "8080:8080"
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ffas_user
      POSTGRES_PASSWORD: ffas_pass
      POSTGRES_DB: ffas
    volumes:
      - ffas_db:/var/lib/postgresql/data
  rabbitmq:
    image: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  ffas_db: